USE DB2025Team03;

/* 뷰 삭제 (먼저) */
DROP VIEW IF EXISTS DB2025_View_TopRatedFacility;
DROP VIEW IF EXISTS DB2025_View_UserActivity;

/* 테이블 삭제 (외래키 참조 순서 고려: 자식 → 부모 순) */
DROP TABLE IF EXISTS DB2025_Favorite;
DROP TABLE IF EXISTS DB2025_Review;
DROP TABLE IF EXISTS DB2025_Reservation;
DROP TABLE IF EXISTS DB2025_Pet;
DROP TABLE IF EXISTS DB2025_Facility;
DROP TABLE IF EXISTS DB2025_User;